from typing import Any, Dict
import pandas as pd
import analysis_tools as tools


def validate_query(plan: Dict[str, Any]) -> Dict[str, Any]:
    """Validate query plan dictionary and raise ValueError if invalid."""
    if not isinstance(plan, dict):
        raise ValueError("Analysis plan must be a dictionary.")

    operation = plan.get("operation")
    if not operation:
        raise ValueError("Analysis plan missing 'operation' field.")

    op = str(operation).lower()

    # Required column checks
    col_ops = {
        "calculate_sum", "sum", "calculate_average", "average", "mean",
        "calculate_min", "min", "calculate_max", "max",
        "calculate_unique_count", "unique_count", "value_counts", "filtered_value_counts"
    }
    col = plan.get("column") or plan.get("value_column") or plan.get("count_column")

    if op in col_ops and not col:
        raise ValueError(f"Operation '{operation}' requires a target column.")

    # Grouped checks
    group_ops = {
        "group_and_sum", "group_sum", "filtered_group_sum",
        "group_and_average", "group_average", "filtered_group_average",
        "group_and_count", "group_count", "top_n", "filtered_top_n",
        "percentage_of_total", "filtered_percentage_of_total"
    }
    group_col = plan.get("group_column") or plan.get("group_by")
    if op in group_ops and not group_col:
        raise ValueError(f"Operation '{operation}' requires 'group_column'.")

    # Top N check
    if op in {"top_n", "filtered_top_n"} and "n" not in plan:
        raise ValueError("Operation 'top_n' requires parameter 'n'.")

    valid_ops = col_ops | group_ops | {
        "calculate_count", "count", "monthly_sum", "filtered_monthly_sum",
        "monthly_average", "filtered_monthly_average", "monthly_count", "filtered_monthly_count"
    }
    
    if op not in valid_ops:
        raise ValueError(f"Unsupported analysis operation: '{operation}'")

    plan["operation"] = op
    return plan


def execute_query(df: pd.DataFrame, plan: Dict[str, Any]) -> Any:
    # sourcery skip: low-code-quality
    """Execute an analysis plan generated by AI against a pandas DataFrame."""
    validated_plan = validate_query(plan)
    operation = validated_plan["operation"]

    col = plan.get("column") or plan.get("value_column") or plan.get("count_column")
    group_col = plan.get("group_column") or plan.get("group_by")
    date_col = plan.get("date_column") or plan.get("date") or "Date"
    filters = plan.get("filters", [])
    n = plan.get("n", 5)

    has_filters = bool(filters)

    match operation:
        case "calculate_sum" | "sum":
            return tools.filtered_sum(df, filters, col) if has_filters else tools.calculate_sum(df, col) # pyright: ignore[reportArgumentType]
        case "calculate_average" | "average" | "mean":
            return tools.filtered_average(df, filters, col) if has_filters else tools.calculate_average(df, col) # pyright: ignore[reportArgumentType]
        case "calculate_count" | "count":
            return tools.filtered_count(df, filters, col) if has_filters else tools.calculate_count(df, col)
        case "calculate_unique_count" | "unique_count":
            return tools.filtered_unique_count(df, filters, col) if has_filters else tools.calculate_unique_count(df, col) # pyright: ignore[reportArgumentType]
        case "calculate_min" | "min":
            return tools.filtered_min(df, filters, col) if has_filters else tools.calculate_min(df, col) # pyright: ignore[reportArgumentType]
        case "calculate_max" | "max":
            return tools.filtered_max(df, filters, col) if has_filters else tools.calculate_max(df, col) # pyright: ignore[reportArgumentType]
        case "group_and_sum" | "group_sum" | "filtered_group_sum":
            return tools.filtered_group_and_sum(df, filters, group_col, col) if has_filters else tools.group_and_sum(df, group_col, col) # pyright: ignore[reportArgumentType]
        case "group_and_average" | "group_average" | "filtered_group_average":
            return tools.filtered_group_and_average(df, filters, group_col, col) if has_filters else tools.group_and_average(df, group_col, col) # pyright: ignore[reportArgumentType]
        case "group_and_count" | "group_count":
            return tools.group_and_count(df, group_col) # pyright: ignore[reportArgumentType]
        case "value_counts" | "filtered_value_counts":
            return tools.filtered_value_counts(df, filters, col) if has_filters else tools.value_counts(df, col) # pyright: ignore[reportArgumentType]
        case "top_n" | "filtered_top_n":
            return tools.filtered_top_n(df, filters, group_col, col, n) if has_filters else tools.top_n(df, group_col, col, n) # pyright: ignore[reportArgumentType]
        case "percentage_of_total" | "filtered_percentage_of_total":
            return tools.filtered_percentage_of_total(df, filters, group_col, col) if has_filters else tools.percentage_of_total(df, group_col, col) # pyright: ignore[reportArgumentType]
        case "monthly_sum" | "filtered_monthly_sum":
            return tools.filtered_monthly_sum(df, filters, date_col, col) if has_filters else tools.monthly_sum(df, date_col, col) # pyright: ignore[reportArgumentType]
        case "monthly_average" | "filtered_monthly_average":
            return tools.filtered_monthly_average(df, filters, date_col, col) if has_filters else tools.monthly_average(df, date_col, col) # pyright: ignore[reportArgumentType]
        case "monthly_count" | "filtered_monthly_count":
            return tools.filtered_monthly_count(df, filters, date_col) if has_filters else tools.monthly_count(df, date_col)
        case _:
            raise ValueError(f"Unsupported analysis operation: '{operation}'")