from typing import Any, Dict
import pandas as pd

import analysis_tools as tools


def execute_query(df: pd.DataFrame, plan: Dict[str, Any]) -> Any:
    """
    Execute an analysis plan generated by AI against a pandas DataFrame.
    
    Routes the plan to the corresponding tool in `analysis_tools.py`.
    """
    if not isinstance(plan, dict):
        raise ValueError("Analysis plan must be a dictionary.")

    operation = plan.get("operation")
    if not operation:
        raise ValueError("Analysis plan missing 'operation' field.")

    # Standardize column mappings across different plan schemas
    col = plan.get("column") or plan.get("value_column") or plan.get("count_column")
    group_col = plan.get("group_column") or plan.get("group_by")
    filters = plan.get("filters", [])
    n = plan.get("n", 5)

    # Convert operator formatting (e.g. "=" to "==") for analysis_tools compatibility
    if filters:
        for f in filters:
            if f.get("operator") == "=":
                f["operator"] = "=="

    # Dispatch logic
    match operation:
        # Unfiltered aggregations
        case "calculate_sum":
            return tools.calculate_sum(df, column=col) # pyright: ignore[reportArgumentType]
        case "calculate_average":
            return tools.calculate_average(df, column=col) # pyright: ignore[reportArgumentType]
        case "calculate_count":
            return tools.calculate_count(df, column=col)
        case "calculate_unique_count":
            return tools.calculate_unique_count(df, column=col) # pyright: ignore[reportArgumentType]
        case "calculate_min":
            return tools.calculate_min(df, column=col) # pyright: ignore[reportArgumentType]
        case "calculate_max":
            return tools.calculate_max(df, column=col) # pyright: ignore[reportArgumentType]
        case "group_and_sum":
            return tools.group_and_sum(df, group_by=group_col, column=col) # pyright: ignore[reportArgumentType]
        case "group_and_average":
            return tools.group_and_average(df, group_by=group_col, column=col) # pyright: ignore[reportArgumentType]
        case "group_and_count":
            return tools.group_and_count(df, group_by=group_col) # pyright: ignore[reportArgumentType]
        case "top_n":
            return tools.top_n(df, group_by=group_col, column=col, n=n) # pyright: ignore[reportArgumentType]
        case "value_counts":
            return tools.value_counts(df, column=col) # pyright: ignore[reportArgumentType]

        # Filtered aggregations
        case "filtered_sum":
            return tools.filtered_sum(df, filters=filters, column=col) # pyright: ignore[reportArgumentType]
        case "filtered_average":
            return tools.filtered_average(df, filters=filters, column=col) # pyright: ignore[reportArgumentType]
        case "filtered_count":
            return tools.filtered_count(df, filters=filters)
        case "filtered_unique_count":
            return tools.filtered_unique_count(df, filters=filters, column=col) # pyright: ignore[reportArgumentType]
        case "filtered_min":
            return tools.filtered_min(df, filters=filters, column=col) # pyright: ignore[reportArgumentType]
        case "filtered_max":
            return tools.filtered_max(df, filters=filters, column=col) # pyright: ignore[reportArgumentType]
        case "filtered_group_and_sum":
            return tools.filtered_group_and_sum(df, filters=filters, group_by=group_col, column=col) # pyright: ignore[reportArgumentType]
        case "filtered_group_and_average":
            return tools.filtered_group_and_average(df, filters=filters, group_by=group_col, column=col) # pyright: ignore[reportArgumentType]
        case "filtered_value_counts":
            return tools.filtered_value_counts(df, filters=filters, column=col) # pyright: ignore[reportArgumentType]
        case "filtered_top_n":
            return tools.filtered_top_n(df, filters=filters, group_by=group_col, column=col, n=n) # pyright: ignore[reportArgumentType]

        case _:
            raise ValueError(f"Unsupported analysis operation: '{operation}'")